version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=uniref
      - POSTGRES_PASSWORD=uniref
      - POSTGRES_DB=uniref
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/pgsql/data
